version: 'latest'

services:
    db:
        image: postgres
        container_name: postgres_container
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
        networks:
            inviteme_network:
                ipv4_address: 172.20.0.2

    nestjs-inviteme:
        image: node
        volumes:
            - .:/usr/src
        container_name: nestjs-inviteme
        restart: always
        ports:
            - '3000:3000'
            - '5555:5555'
        environment:
            - DATABASE_URL=postgresql://myuser:mypassword@172.20.0.2:5432/mydb?schema=public
        networks:
            inviteme_network:
                ipv4_address: 172.20.0.3
        depends_on:
            - db
        working_dir: /usr/src/app
        command: sh -c "npm install && npm run prisma:generate:local && npm run start:dev"
networks:
    inviteme_network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16